cache:
  paths:
    - node_modules/

build:
  stage: build
  image: electronuserland/builder:wine
  only:
    - master
  script:
    - npm install
    - npm run electron:build-win
  artifacts:
    paths:
      - dist/*.exe*
      - dist/*.yml
    expire_in: 1 month

pages:
  stage: deploy
  image: alpine:latest
  only:
    - master
  dependencies:
    - build
  script:
    - cp dist/*.exe* dist/*.yml public
  artifacts:
    paths:
      - public
